modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="LGPL v3"
[[mods]] #mandatory
modId="serverpacklocatorutility" #mandatory
version="1.0.0" #mandatory
displayName="Server Pack Locator Utility mod" #mandatory
credits="cpw" #optional
authors="cpw" #optional
description='''
Server Pack Locator Utility mod.

This mod is distributed as part of the ServerPackLocator to allow interaction with the game.
'''
